### ISSUE TITLE
Wrong character coding

### ISSUE THREAD

**Issue by mz-pdm** [m-czernek/acrobot#5] opened 2019-05-29 16:10 UTC
I'm not sure whether it's a problem of Acrobot or the given database, but I get the following response on "RSVP" in Firefox 60:

RÃ©pondez s'il vous plaÃ®t - please, respond

**Comment by m-czernek** [comment] 2019-05-29 17:00
Thank you for noticing! At this point, I am aware that Acrobot does not support non-English characters, but I'll look into it.

**Comment by m-czernek** [comment] 2019-05-29 17:35
Actually, the issue indeed is in the DB, caused by my python script. I have added a correct explanation, and will drop the incorrect one later. Thank you once again for noticing; closing as resolved.

**Closed** 2019-05-29 18:45 UTC

**Comment by m-czernek** [comment] 2019-06-11 13:59
Just an FYI, the old corrupted text has been removed. Only the correct one remains:

![image](https://user-images.githubusercontent.com/16302538/59278196-da147180-8c61-11e9-89f7-e3b682ca6799.png)
